import SwiftUI
import UIKit

struct InspectionShareContent {
    let resultText: String
    let displayImage: UIImage?
    let photoImage: UIImage?

    var condition: BatteryCondition {
        BatteryCondition(from: resultText)
    }

    var explanation: String {
        condition.shortExplanation
    }

    var safetyReminder: String {
        switch condition {
        case .normal:
            return "Continue storing and handling the pouch cell carefully. Recheck it if heat, odor, or swelling appears."
        case .bulging:
            return "Stop using or charging this cell. Move it away from flammable materials and follow local safety guidance."
        case .unknown:
            return "Re-scan with better lighting and focus. If swelling is suspected, treat the cell as potentially unsafe."
        }
    }

    var shareText: String {
        """
        Pouch Cell Inspector
        Inspection Result: \(condition.displayName)
        \(explanation)
        """
    }

    var imageForSharing: UIImage? {
        photoImage ?? displayImage
    }
}

struct InspectionActivityItems: Identifiable {
    let id = UUID()
    let items: [Any]
}

struct ActivityView: UIViewControllerRepresentable {
    let items: [Any]

    func makeUIViewController(context: Context) -> UIActivityViewController {
        UIActivityViewController(activityItems: items, applicationActivities: nil)
    }

    func updateUIViewController(_ uiViewController: UIActivityViewController, context: Context) { }
}

enum InspectionShareCardRenderer {
    static func makeCard(for content: InspectionShareContent) -> UIImage {
        let size = CGSize(width: 1080, height: 1480)
        let format = UIGraphicsImageRendererFormat()
        format.scale = 2
        format.opaque = true

        let renderer = UIGraphicsImageRenderer(size: size, format: format)
        return renderer.image { context in
            let cgContext = context.cgContext
            let bounds = CGRect(origin: .zero, size: size)

            UIColor(red: 0.96, green: 0.98, blue: 0.99, alpha: 1).setFill()
            cgContext.fill(bounds)

            let outerCard = CGRect(x: 64, y: 64, width: size.width - 128, height: size.height - 128)
            roundedFill(rect: outerCard, radius: 36, color: .white)
            roundedStroke(rect: outerCard, radius: 36, color: UIColor(red: 0.74, green: 0.81, blue: 0.85, alpha: 1), lineWidth: 3)

            drawText(
                "Pouch Cell Inspector",
                in: CGRect(x: 112, y: 112, width: size.width - 224, height: 54),
                font: .systemFont(ofSize: 34, weight: .semibold),
                color: UIColor(red: 0.12, green: 0.16, blue: 0.18, alpha: 1)
            )

            drawText(
                "Generated by Pouch Cell Inspector",
                in: CGRect(x: 112, y: size.height - 154, width: size.width - 224, height: 36),
                font: .systemFont(ofSize: 22, weight: .regular),
                color: UIColor(red: 0.42, green: 0.48, blue: 0.52, alpha: 1),
                alignment: .center
            )

            let imageRect = CGRect(x: 112, y: 202, width: size.width - 224, height: 470)
            if let image = content.imageForSharing {
                roundedClip(rect: imageRect, radius: 28) {
                    UIColor(red: 0.73, green: 0.81, blue: 0.86, alpha: 1).setFill()
                    cgContext.fill(imageRect)
                    drawAspectFill(image, in: imageRect)
                }
            } else {
                roundedFill(rect: imageRect, radius: 28, color: UIColor(red: 0.73, green: 0.81, blue: 0.86, alpha: 1))
                drawText(
                    "No photo available",
                    in: imageRect.insetBy(dx: 32, dy: 200),
                    font: .systemFont(ofSize: 30, weight: .medium),
                    color: UIColor(red: 0.12, green: 0.16, blue: 0.18, alpha: 1),
                    alignment: .center
                )
            }

            drawText(
                "Inspection Result",
                in: CGRect(x: 112, y: 734, width: size.width - 224, height: 46),
                font: .systemFont(ofSize: 34, weight: .semibold),
                color: UIColor(red: 0.12, green: 0.16, blue: 0.18, alpha: 1)
            )

            let badgeRect = CGRect(x: 112, y: 810, width: size.width - 224, height: 92)
            roundedFill(rect: badgeRect, radius: 22, color: badgeColor(for: content.condition))
            drawText(
                content.condition.displayName,
                in: badgeRect.insetBy(dx: 28, dy: 22),
                font: .systemFont(ofSize: 36, weight: .bold),
                color: .white
            )

            drawText(
                content.explanation,
                in: CGRect(x: 112, y: 942, width: size.width - 224, height: 150),
                font: .systemFont(ofSize: 30, weight: .regular),
                color: UIColor(red: 0.18, green: 0.22, blue: 0.25, alpha: 1)
            )

            let reminderRect = CGRect(x: 112, y: 1132, width: size.width - 224, height: 156)
            roundedFill(rect: reminderRect, radius: 24, color: UIColor(red: 0.90, green: 0.94, blue: 0.96, alpha: 1))
            drawText(
                "Safety Reminder",
                in: CGRect(x: 144, y: 1160, width: size.width - 288, height: 32),
                font: .systemFont(ofSize: 24, weight: .semibold),
                color: UIColor(red: 0.12, green: 0.16, blue: 0.18, alpha: 1)
            )
            drawText(
                content.safetyReminder,
                in: CGRect(x: 144, y: 1202, width: size.width - 288, height: 68),
                font: .systemFont(ofSize: 24, weight: .regular),
                color: UIColor(red: 0.18, green: 0.22, blue: 0.25, alpha: 1)
            )
        }
    }

    private static func badgeColor(for condition: BatteryCondition) -> UIColor {
        switch condition {
        case .normal:
            return UIColor(red: 0.17, green: 0.55, blue: 0.33, alpha: 1)
        case .bulging:
            return UIColor(red: 0.76, green: 0.18, blue: 0.18, alpha: 1)
        case .unknown:
            return UIColor(red: 0.72, green: 0.42, blue: 0.10, alpha: 1)
        }
    }

    private static func drawAspectFill(_ image: UIImage, in rect: CGRect) {
        let imageSize = image.size
        guard imageSize.width > 0, imageSize.height > 0 else { return }

        let scale = max(rect.width / imageSize.width, rect.height / imageSize.height)
        let drawSize = CGSize(width: imageSize.width * scale, height: imageSize.height * scale)
        let drawOrigin = CGPoint(
            x: rect.midX - drawSize.width / 2,
            y: rect.midY - drawSize.height / 2
        )

        image.draw(in: CGRect(origin: drawOrigin, size: drawSize))
    }

    private static func drawText(
        _ text: String,
        in rect: CGRect,
        font: UIFont,
        color: UIColor,
        alignment: NSTextAlignment = .left
    ) {
        let paragraphStyle = NSMutableParagraphStyle()
        paragraphStyle.alignment = alignment
        paragraphStyle.lineBreakMode = .byWordWrapping

        let attributes: [NSAttributedString.Key: Any] = [
            .font: font,
            .foregroundColor: color,
            .paragraphStyle: paragraphStyle
        ]

        NSString(string: text).draw(with: rect, options: [.usesLineFragmentOrigin, .usesFontLeading], attributes: attributes, context: nil)
    }

    private static func roundedFill(rect: CGRect, radius: CGFloat, color: UIColor) {
        color.setFill()
        UIBezierPath(roundedRect: rect, cornerRadius: radius).fill()
    }

    private static func roundedStroke(rect: CGRect, radius: CGFloat, color: UIColor, lineWidth: CGFloat) {
        color.setStroke()
        let path = UIBezierPath(roundedRect: rect, cornerRadius: radius)
        path.lineWidth = lineWidth
        path.stroke()
    }

    private static func roundedClip(rect: CGRect, radius: CGFloat, drawing: () -> Void) {
        let path = UIBezierPath(roundedRect: rect, cornerRadius: radius)
        path.addClip()
        drawing()
    }
}
